### ISSUE TITLE
Global configuration option to change default window dimensions

### ISSUE THREAD

**Issue by josephjeno** [os-js/osjs-filemanager-application#10]
It would be great to have an option in config to specify the default application window dimensions. On a large monitor the file manager is a wee baby window way up in the corner, necessitating a manual resize every time the application is opened.

![image](https://user-images.githubusercontent.com/29079278/70639593-b201cd00-1c08-11ea-9480-a2e0dc24746c.png)

**Comment by andersevenrud** [comment]
I'll look into this after I've had my dinner :)

**Comment by andersevenrud** [comment]
I've published a new version that supports adding the following to global config (`src/client/config.js`):

```
{
  filemanager: {
    defaultWindowSize: {width: 800, height: 600}
  }
}
```

Tip: Window dimensions supports percentages:

```
{
  filemanager: {
    defaultWindowSize: {width: 0.5, height: 0.5} // 50% of viewport
  }
}
```

*I found a [bug](https://github.com/os-js/osjs-client/issues/87) in this though. Using 100% (1.0) does not work, but anything below that is OK*

**Comment by josephjeno** [comment]
Thanks so much man, this works great of course.
