### ISSUE TITLE
Add "Date modified" column to File Manager and FileDialog

### ISSUE THREAD

**Issue by josephjeno** [os-js/osjs-filemanager-application#11]
It would be very helpful if OS.js included a Date modified column. We use a few apps in OS.js that generate long, very similarly named MATLAB files. Before long it becomes difficult to navigate. 

![image](https://user-images.githubusercontent.com/29079278/73076867-00072300-3e8d-11ea-854a-1c62729cbd49.png)

**Comment by andersevenrud** [comment]
The VFS file objects have timestamps, so it could be added as a column:

* https://github.com/os-js/osjs-filemanager-application/blob/master/index.js#L162
* https://github.com/os-js/osjs-filemanager-application/blob/master/index.js#L467

The `stat` property of a VFS file contains the following: https://nodejs.org/api/fs.html#fs_class_fs_stats

It would probably be best to make this column trigger via an application setting that is selectable from a menu or something.

**Comment by andersevenrud** [comment]
> It would probably be best to make this column trigger via an application setting that is selectable from a menu or something.

Just because the columns cannot currently be resized, and the date string might be pretty long.

**Comment by josephjeno** [comment]
Maybe some sort of right click context menu on the column headers?

![image](https://user-images.githubusercontent.com/29079278/73080420-cd145d80-3e93-11ea-9b36-83bd58ec92a5.png)

**Comment by andersevenrud** [comment]
Or maybe just the "View" menu :thinking:

**Comment by andersevenrud** [comment]
I've started on this here: https://github.com/os-js/osjs-filemanager-application/pull/12

However, this application needs a bit of a cleanup as well as persistent settings :thinking:

**Comment by andersevenrud** [comment]
@josephjeno I've started a refactor of this application here: https://github.com/os-js/osjs-filemanager-application/pull/14

This will be included in that update :)

**Comment by andersevenrud** [comment]
@josephjeno Feel free to test out that branch for yourself. I think I got everything working as it was, but needs testing :slightly_smiling_face:

**Comment by josephjeno** [comment]
Ran it through the paces this morning and everything works great after the cleanup. Persistent settings would be awesome. Currently it forgets my view settings (show hidden files, show date column) after closing and reopening the app.

**Comment by andersevenrud** [comment]
Cool! Persistent settings is supported in apps, so technically I just have to wire it up and run a save method. I'll fix that asap :)

**Comment by andersevenrud** [comment]
@josephjeno I just pushed another commit that makes settings persistent. So if you wanna give that a go, it's there waiting for you ;)

Should I make it so that all open FileManager instances gets updated whenever you change a setting ? :thinking:

**Comment by josephjeno** [comment]
Good question! I messed around with Windows File Explorer settings and changes to **Display Hidden Items** and **Display File Name Extensions** is reflected immediately across all instances. That... makes sense to me I think. For the most part I think our users will just set the settings once and leave it.

**Comment by andersevenrud** [comment]
I uncommented the line required for that to work. So if you try again it should be reflected across all open instances :)

**Comment by josephjeno** [comment]
It's working perfect man!

**Comment by andersevenrud** [comment]
Nice :) I'll do another run through of all the features after the refactor, then release it (tomorrow probably).

**Comment by josephjeno** [comment]
Thanks so much Anders, have a great weekend!

**Comment by andersevenrud** [comment]
1.4.0 is now out :)
