### ISSUE TITLE
unnecessary invoking function

### ISSUE THREAD

**Issue by msjavan** [os-js/osjs-filemanager-application#13]
Every time I opened any menu in filemanager, getMenuMountpoints function invoked. This is not an optimal job. I think It should be invoked just if "Go" menu selected.

**Comment by andersevenrud** [comment]
This is because the mountpoints is not [currently] stored in the application state.
And seeing how `getMenuMountpoints` only maps an array, it doesn't really cost anything.

However, feel free to submit a patch for this is you want.

**Comment by andersevenrud** [comment]
I've started a refactor of this application here: https://github.com/os-js/osjs-filemanager-application/pull/14

So this won't be an issue anymore (soon) :)

**Comment by andersevenrud** [comment]
This change is now out :)
