### ISSUE TITLE
Deprecate static default window option configuration

### ISSUE THREAD

**Issue by andersevenrud** [os-js/osjs-filemanager-application#20]
This will revert the following:

https://github.com/os-js/osjs-filemanager-application/commit/edbb11805fbe73b7e164a93bec0b6cdad616564b

And instead use the following:

https://github.com/os-js/osjs-client/pull/116

**Comment by andersevenrud** [comment]
@josephjeno Just a small heads-up on this as I thought you might find it useful.

TL;DR: I'm adding configuration options to override arbitrary windows default options. This will make the default File Manager window size override via client configuration that I made for you obsolete.

I'll keep the customization for a while so you'll have good time to migrate the changes :). The updates in `@osjs/client` won't break anything for you anyways, so it's totally safe and just requires a minor change to your `src/client/config.js` file.

**Comment by josephjeno** [comment]
Ah thanks man for the heads up! Hope all is well with you.

**Comment by andersevenrud** [comment]
@josephjeno I just updated the linked PR with a bit more detained information about the workings of this.

I'm doing very well, thank you. I hope you're doing well too :smile:

**Comment by ajmeese7** [comment]
@andersevenrud since the linked PR has been merged, is this issue good to be closed out?

**Comment by andersevenrud** [comment]
Yup @ajmeese7 . The PR didn't contain a  fixes reference so this was not auto-closed.
