### ISSUE TITLE
change default mount points

### ISSUE THREAD

**Issue by msjavan** [os-js/osjs-filemanager-application#24]
How can I change default mount points of file manager? (i.e. Rename / Remove)

![image](https://user-images.githubusercontent.com/5146431/86452639-d6063680-bd31-11ea-8157-67f83784fa79.png)

**Comment by andersevenrud** [comment]
Copy this into your local configuration: https://github.com/os-js/osjs-client/blob/master/src/config.js#L235

Then in your bootstrap https://github.com/os-js/OS.js/blob/master/src/client/index.js#L58 you can do:

```
const osjs = new Core(config, {
  omit: ['vfs.mountpoints']
});
```
