### ISSUE TITLE
Folder names cut short in the left pane

### ISSUE THREAD

**Issue by valp124** [os-js/osjs-filemanager-application#35]
It would super cool to see full folder names in the left pane of the File Manager. Example of how the names get cut short:

![image](https://user-images.githubusercontent.com/7969539/123850784-6bf28400-d8e8-11eb-9bc0-fa58c03f71f4.png)

(Note that expanding the pane doesn't have an effect on the width of the names column.)

Only if it's not too much work!

**Comment by andersevenrud** [comment]
The pane expansion should take care of the expansion :thinking: What browser are you on here ? 

Also, can you reproduce this on https://demo.os-js.org/ ?

**Comment by andersevenrud** [comment]
Just pinging you here because I'm doing a cleanup of stale issues :blush:

**Comment by valp124** [comment]
Interesting. I'm seeing this on Chrome and Edge, haven't tested FF. BUT:  https://demo.os-js.org/ works just fine in Edge. So what might I be doing wrong?...

**Comment by andersevenrud** [comment]
> Edge

If you have the latest Edge, then it's basically Chrome, so it should be identical here now (thankfully).

> So what might I be doing wrong?...

Might not be doing anything wrong. My immediate thought here is that there might be some custom CSS that is not scoped correctly and bleeds over to a GUI component or something in the Filemanager layout.

**Comment by valp124** [comment]
Ah, could be. Let me see if I can spot anything in the dev tools...

**Comment by andersevenrud** [comment]
If you know your way around devtools DOM inspector, then you can mark the icon or text inside a row, then go downward until you get to the element that should be 100% wide (will be obvious, because all elements should be 100% wide there). Then screenshot the CSS rules to me.

**Comment by valp124** [comment]
I don't see that anything is bleeding... Here it is, let me know if you want to see more.

![image](https://user-images.githubusercontent.com/7969539/126846426-8a01b469-5c74-4cf9-8160-20092a07a637.png)

**Comment by andersevenrud** [comment]
Hm. Don't really see anything. Would it be possible to do a TeamViewer or something (and send me the login via Gitter) ?

**Comment by valp124** [comment]
Sure thing. TeamViewer is blocked for me, but Hangouts maybe?

**Comment by andersevenrud** [comment]
Let's continue this discussion on Gitter :nerd_face:

**Comment by valp124** [comment]
Sure

**Comment by andersevenrud** [comment]
> My immediate thought here is that there might be some custom CSS that is not scoped correctly

Even if my memory is going, my instincts are still on point :joy:
