### ISSUE TITLE
When downloading files, the name on the client is always "readfile"

### ISSUE THREAD

**Issue by valp124** [os-js/osjs-filemanager-application#6]
Downloading any file from the File Manager results in a local file called "readfile." 
(I tried testing this from the official demo site, to make sure it's not only our instance that does that, but there I get "File not found" for all files.)

**Comment by andersevenrud** [comment]
Aha. I believe this is because the server does not send back a spesific header to let the browser know the filename. It takes `readfile` which is the last part of the URL path.

Could you move this issue to the osjs-server repository with my comment in mind ? :)

**Comment by valp124** [comment]
Closing and moving to osjs-server
